[tool.black]
target-versions = ["py37", "py38", "py39", "py310"]
include = '''
    (
        \.py$
        | \.py\.in$
        | src/firewall-applet.in
        | src/firewall-cmd.in
        | src/firewall-config.in
        | src/firewalld.in
        | src/firewall-offline-cmd.in
    )
    '''
