name: source code and build checks
on: [push, pull_request]

jobs:
  check:
    env:
      apt-dependencies: |
        autoconf automake docbook-xml docbook-xsl ebtables intltool ipset \
        iptables libdbus-1-dev libgirepository1.0-dev libglib2.0-dev \
        libxml2-utils nftables pkg-config python3-nftables xsltproc
      pip-dependencies: |
        decorator dbus-python PyGObject flake8

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: apt install dependencies
        run: sudo apt install -y ${{ env.apt-dependencies }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ env.pip-dependencies }}

      - name: install python-slip-dbus
        run: |
          cd /tmp
          wget --retry-connrefused https://github.com/nphilipp/python-slip/releases/download/python-slip-0.6.5/python-slip-0.6.5.tar.bz2
          tar xf python-slip-0.6.5.tar.bz2
          cd python-slip-0.6.5
          make
          python ./setup.py install

      - name: build firewalld
        run: |
          ./autogen.sh
          ./configure
          make -j $(nproc)

      - name: check source code
        run: |
          make -C src check-local

      - name: check config files
        run: |
          make -C config check-local
